import streamlit as st
import pandas as pd
import json
from PIL import Image
from src.pipeline.predict_pipeline import PredictionPipeline
from src.utils.common import logger


st.set_page_config(
    page_title="Customer Segmentation",
    page_icon="👥",
    layout="wide"
)


try:
    with open('artifacts/model_evaluation/metrics.json', 'r') as f:
        metrics = json.load(f)
    silhouette_score = metrics.get('silhouette_score', 'N/A')
except FileNotFoundError:
    silhouette_score = "N/A (Run training pipeline first)"

try:
    
    plot_image = Image.open('artifacts/model_evaluation/silhouette_plot.png')
except FileNotFoundError:
    plot_image = None


@st.cache_resource
def get_prediction_pipeline():
    try:
        pipeline = PredictionPipeline()
        logger.info("Prediction pipeline loaded for Streamlit app.")
        return pipeline
    except Exception as e:
        logger.error(f"Failed to load prediction pipeline: {e}")
        st.error(f"Failed to load model artifacts: {e}. Have you run the training pipeline?")
        return None

pipeline = get_prediction_pipeline()


st.title("👥 Customer Segmentation App")
st.markdown("This app uses a **Spectral Clustering** model (our notebook champion!) to segment customers based on their **RFM** scores.")


col1, col2 = st.columns([1, 1])


with col1:
    st.header("🔮 Predict New Customer")
    st.markdown("Adjust the sliders to represent a customer's RFM profile.")
    
    
    recency = st.slider(
        "Recency (Days since last purchase)", 
        min_value=1, max_value=400, value=50,
        help="How many days ago was their last purchase?"
    )
    
    frequency = st.slider(
        "Frequency (Total number of purchases)", 
        min_value=1, max_value=250, value=5,
        help="How many separate transactions have they made?"
    )
    
    monetary = st.slider(
        "Monetary (Total spend)", 
        min_value=1, max_value=300000, value=1500,
        help="How much total money have they spent?"
    )
    
    if st.button("Segment Customer", use_container_width=True):
        if pipeline:
           
            input_data = pd.DataFrame(
                [[recency, frequency, monetary]],
                columns=['Recency', 'Frequency', 'Monetary']
            )
            
            
            prediction = pipeline.predict(input_data)
            
            
            st.success(f"**Predicted Segment: Cluster {prediction}**")
            st.balloons()
        else:
            st.error("Prediction engine is not available. Please check the logs.")


with col2:
    st.header("📊 Model Performance")
    
    
    st.metric(
        label="Final Silhouette Score", 
        value=f"{silhouette_score:.4f}"
    )
    st.markdown("Our benchmark proved Spectral Clustering (`sc`) was superior to K-Means. A score closer to 1 indicates well-separated clusters.")
    
   
    if plot_image:
        st.image(plot_image, caption="Final Cluster Plot (Generated by Evaluation Component)")
    else:
        st.warning("Cluster plot not found. Run the training pipeline (`python main.py`) to generate it.")